### ISSUE TITLE
Feature request: extract functions

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/libuast#14]
I see the same recurring problem in our team: we take a UAST and extract all the functions.

So it looks like a great feature to have, so that we do not reinvent it again and again:

1. Given a UAST, compose the list of all the function objects.
2. Every found function object shall contain: lineno begin, lineno end, name, inner UAST subtree, reference to owning class node if eligible.

**Comment by zurk** [comment]
Yes, It would be great!
Now I have this generic function to do this. 
https://github.com/src-d/snippet-ranger/blob/master/snippet_ranger/utils.py#L25

**Comment by EgorBu** [comment]
I think it will be great not to limit this functionality to only "functions".
Ex: extract classes, decorators, loops, etc

**Comment by vmarkovtsev** [comment]
@egorbu Some languages do not have classes (C, Go), decorators and others. Loops should be addressed in a different request and somewhere in the future. Let's keep the scope as narrow as possible so that we can actually have it implemented.

**Comment by abeaumont** [comment]
Functions (as well as other language features), should be extracted using xpath queries.
We'll add some documentation on xpath filters, but providing specific extractors is out of the scope of this project.

**Comment by abeaumont** [comment]
Created #20 to handle this documentation.
