### ISSUE TITLE
Feature request: function to filter invisible nodes

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/libuast#33]
While I was implementing the tree diff, it became clear that the following function will be very useful for people who want to use UAST to perform source code highlighting:

> Throw away all the nodes which do not have a position - that is, are not related to any specific token.

Such tokens can be safely discarded during the highlight traversal. **Of course, root nodes may not be thrown away - they may have visible children.** I don't see how it can be performed with XPath... Can it?

**Comment by abeaumont** [comment]
Thanks for the feature request @vmarkovtsev. It's not possible to do this filtering with xpath queries, since the the position is currently not included in the XML node that is using for filtering.
