### ISSUE TITLE
improve error reporting

### ISSUE THREAD

**Issue by mcuadros** [bblfsh/libuast#42]
When an error happens applying a xpath, the error returned is : "error: UastFilter() failed".
But the detailed error is pritned to the stderr/stdout: "xmlXPathCompOpEval: function reverse not found"

The expected error should contain the information printed, and not a generic error. And never print information to the stdout or stderr.

**Comment by abeaumont** [comment]
@mcuadros the error is printed by `libxml2`. Will try to improve error reporting though.
