### ISSUE TITLE
Complete the move to C++ (14?)

### ISSUE THREAD

**Issue by juanjux** [bblfsh/libuast#56]
Currently the code is a mix of C and C++. It would be desirable to move everything (except the C interface) to modern C++. [This discarded commit](https://github.com/bblfsh/libuast/commit/ce0c80ffdbb2127549ebc3a9c26c28950622344a) has a working Travis config to use a modern g++ version (it uses version 6 but 7 works too).

We also could use libxml++ that is the C++ oriented version of libxml2.

**Comment by vmarkovtsev** [comment]
`libxml++` adds yet another library which we will have to compile on Windows.

**Comment by vmarkovtsev** [comment]
c++14 is implemented inn GCC 5+: https://gcc.gnu.org/projects/cxx-status.html

So I think c++14 is OK to require. GCC 5 can be installed on Xenial without any additional PPAs.

**Comment by juanjux** [comment]
If we move to libxml++ it would remove one library (libxml2) from another one, but this is very very low priority right now (and for discussion) with all the pending work and the "human resources" in the team :) By the way, thanks for your PRs.

I had problems with some C++ code on GCC 5 and Travis, thus the change to G++6 in that discarded commit, but we could re-examine again if needed. I think it was related to `unordered_map` not hashing pointers automatically in version 5 (at the end we just added the hashing ourselves and finally removed that map, so it was no showstopper).

**Comment by juanjux** [comment]
Moving to Go so closing this.
