### ISSUE TITLE
Add documentation for XPath functions

### ISSUE THREAD

**Issue by juanjux** [bblfsh/libuast#66]
XPath 1.0 functions were implemented in #55 but it's still undocumented.

**Comment by juanjux** [comment]
Closing, the issue is in the wrong project, it should be in bblfsh/documentation.

**Comment by dennwc** [comment]
@juanjux Please create a new issue and link it here

**Comment by juanjux** [comment]
There is already a PR:

bblfsh/documentation/pull/143
