### ISSUE TITLE
Debían packages

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/libuast#95]
This is the reincarnation of #21
I request distribution packages for Debian. I will be happy to PR the required configuration files and maintain the Ubuntu PPA, if needed.

**Comment by juanjux** [comment]
Question:

Why do you need this for? Clients now statically compile libuast into their extension modules so they don't include a libuast dll as before (neither will they use it).

**Comment by vmarkovtsev** [comment]
@juanjux So the dynamic linking is not supported anymore?

**Comment by vmarkovtsev** [comment]
But anyway, I want to have `python3-uast`, `libuast-dev` (C++ client) and `golang-uast` in Ubuntu mainline.

**Comment by vmarkovtsev** [comment]
For sure these packages are not required for ML tasks and we happily and successfully live without them. This issue is a generic "play nice with OSS community" feature.

**Comment by bzz** [comment]
As in https://github.com/bblfsh/libuast/issues/21#issuecomment-442135023

From a quick offline discussion with @vmarkovtsev we figured that 2 offspring of this issue are in order:
 - a new issue in bblfshd repo .deb packaging for the bbflshd
 - a new issue in python client for `apt-get install` (same to many other mature python libs)

so I suggest closing this issue as from what I understood these requirements has nothing to do with libuast and move discussion to bblfshd/lib repos with particular use cases, etc.

**Comment by dennwc** [comment]
OK, this sounds reasonable now :) Closing.

**Comment by bzz** [comment]
Cool!
@vmarkovtsev would you be so kind to later of file 2 issues for packaging bblfshd and python-clinet?
I think you will describe the use case and rationale much better then I can.
